name: helpingpaw_frontend
description: "helpingPaw - Abschlussprojekt"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.6
  # Weitere Firebase-Pakete je nachdem, was du brauchst

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/paw.png

  fonts:
    - family: Jersey
      fonts:
        - asset: assets/fonts/Jersey15-Regular.ttf