name: helpingpaw_frontend
description: "helpingPaw - Abschlussprojekt"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:

  # Verschlüsselung
  crypto: ^3.0.3
  encrypt: ^5.0.1

  flutter:
    sdk: flutter

  # Firebase-Packages (deine ursprünglichen Versionen)
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.0

  # Nur Audio - KEINE Notifications mehr!
  audioplayers: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/  # Für plumScream.m4a Sound-Datei

  fonts:
    - family: Jersey
      fonts:
        - asset: assets/fonts/Jersey15-Regular.ttf



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/pawlogo.png"
  background_color: "0xFFC7F0EC"